"""initial schema

Revision ID: f83d1aa88f06
Revises: 
Create Date: 2026-07-16 00:10:26.748177+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f83d1aa88f06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='recordstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employees_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='recordstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=True)

    op.create_table('project_artifacts',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artifact_type', sa.Enum('DOCUMENT', 'DIAGRAM', 'SPECIFICATION', 'SOURCE_REPO', 'DATASET', 'MODEL', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_artifacts_project_id'), ['project_id'], unique=False)

    op.create_table('project_capabilities',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('capability_type', sa.Enum('API', 'EVENT_PUBLISH', 'EVENT_CONSUMER', 'ETL', 'VECTOR_DATABASE', 'MCP_SERVER', name='capabilitytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('details', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_capabilities_project_id'), ['project_id'], unique=False)

    op.create_table('project_client_groups',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_client_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_client_groups_project_id'), ['project_id'], unique=False)

    op.create_table('project_dependency_groups',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_dependency_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_dependency_groups_project_id'), ['project_id'], unique=False)

    op.create_table('project_domains',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_domain_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_domain_id'], ['project_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_domains', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_domains_parent_domain_id'), ['parent_domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_domains_project_id'), ['project_id'], unique=False)

    op.create_table('project_knowledge_bases',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kb_type', sa.Enum('WIKI', 'CONFLUENCE', 'VECTOR_STORE', 'DOCUMENT_SET', 'FAQ', 'RUNBOOK', 'OTHER', name='knowledgebasetype'), nullable=False),
    sa.Column('location', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_knowledge_bases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_knowledge_bases_project_id'), ['project_id'], unique=False)

    op.create_table('project_roles',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_project_role_name')
    )
    with op.batch_alter_table('project_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_roles_project_id'), ['project_id'], unique=False)

    op.create_table('project_tech_stacks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('LANGUAGE', 'FRAMEWORK', 'DATABASE', 'RULE_ENGINE', 'LIBRARY', 'PLATFORM', 'TOOL', 'OTHER', name='techstackcategory'), nullable=False),
    sa.Column('version', sa.String(length=60), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_tech_stacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_tech_stacks_project_id'), ['project_id'], unique=False)

    op.create_table('project_clients',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('client_project_id', sa.Uuid(), nullable=False),
    sa.Column('client_capability_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_capability_id'], ['project_capabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['project_client_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_clients_client_capability_id'), ['client_capability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_clients_client_project_id'), ['client_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_clients_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_clients_project_id'), ['project_id'], unique=False)

    op.create_table('project_dependencies',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_project_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_capability_id', sa.Uuid(), nullable=True),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_capability_id'], ['project_capabilities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['depends_on_project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['project_dependency_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_dependencies_depends_on_capability_id'), ['depends_on_capability_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependencies_depends_on_project_id'), ['depends_on_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependencies_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_dependencies_project_id'), ['project_id'], unique=False)

    op.create_table('project_employees',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_percent', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['project_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'employee_id', 'role_id', name='uq_project_employee_role')
    )
    with op.batch_alter_table('project_employees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_employees_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_employees_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_employees_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_employees_role_id'))
        batch_op.drop_index(batch_op.f('ix_project_employees_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_employees_employee_id'))

    op.drop_table('project_employees')
    with op.batch_alter_table('project_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_dependencies_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_dependencies_group_id'))
        batch_op.drop_index(batch_op.f('ix_project_dependencies_depends_on_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_dependencies_depends_on_capability_id'))

    op.drop_table('project_dependencies')
    with op.batch_alter_table('project_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_clients_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_clients_group_id'))
        batch_op.drop_index(batch_op.f('ix_project_clients_client_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_clients_client_capability_id'))

    op.drop_table('project_clients')
    with op.batch_alter_table('project_tech_stacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_tech_stacks_project_id'))

    op.drop_table('project_tech_stacks')
    with op.batch_alter_table('project_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_roles_project_id'))

    op.drop_table('project_roles')
    with op.batch_alter_table('project_knowledge_bases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_knowledge_bases_project_id'))

    op.drop_table('project_knowledge_bases')
    with op.batch_alter_table('project_domains', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_domains_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_domains_parent_domain_id'))

    op.drop_table('project_domains')
    with op.batch_alter_table('project_dependency_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_dependency_groups_project_id'))

    op.drop_table('project_dependency_groups')
    with op.batch_alter_table('project_client_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_client_groups_project_id'))

    op.drop_table('project_client_groups')
    with op.batch_alter_table('project_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_capabilities_project_id'))

    op.drop_table('project_capabilities')
    with op.batch_alter_table('project_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_artifacts_project_id'))

    op.drop_table('project_artifacts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_name'))

    op.drop_table('projects')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employees_email'))

    op.drop_table('employees')
    # ### end Alembic commands ###
