"""initial ingest_log

Revision ID: b194f737190d
Revises: 
Create Date: 2026-07-16 01:28:16.349585+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b194f737190d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_log',
    sa.Column('ref_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('project_sprint', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('ingest_type', sa.Enum('PDF', 'EXCEL', 'CSV', 'IMAGE', 'OTHER', name='ingesttype'), nullable=False),
    sa.Column('storage_type', sa.Enum('LOCAL_FILE_SYSTEM', 'AWS_S3', 'AZURE_BLOB', 'OTHER', name='storagetype'), nullable=False),
    sa.Column('storage_location', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('ingest_process_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='ingestprocessstatus'), nullable=False),
    sa.Column('ingest_dt', sa.DateTime(), nullable=True),
    sa.Column('ingest_process_start_dt', sa.DateTime(), nullable=True),
    sa.Column('ingest_process_complete_dt', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_log_ingest_process_status'), ['ingest_process_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_log_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_log_ref_id'), ['ref_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_log_ref_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_log_project_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_log_ingest_process_status'))

    op.drop_table('ingest_log')
    # ### end Alembic commands ###
