"""initial workspace

Revision ID: 6e0064762d3d
Revises: 
Create Date: 2026-07-16 01:41:25.346790+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e0064762d3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'CANCELLED', name='workitemstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_epics_project_id'), ['project_id'], unique=False)

    op.create_table('releases',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'RELEASED', 'CANCELLED', name='releasestatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_releases_project_id'), ['project_id'], unique=False)

    op.create_table('sprints',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'CLOSED', name='sprintstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprints_project_id'), ['project_id'], unique=False)

    op.create_table('workspace_memberships',
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email', 'project_id', name='uq_membership_user_project')
    )
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_memberships_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_memberships_user_email'), ['user_email'], unique=False)

    op.create_table('features',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('epic_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'CANCELLED', name='workitemstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_epic_id'), ['epic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_features_project_id'), ['project_id'], unique=False)

    op.create_table('stories',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('feature_id', sa.Uuid(), nullable=True),
    sa.Column('sprint_id', sa.Uuid(), nullable=True),
    sa.Column('release_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED', 'CANCELLED', name='workitemstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_release_id'), ['release_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_sprint_id'), ['sprint_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_stories_release_id'))
        batch_op.drop_index(batch_op.f('ix_stories_project_id'))
        batch_op.drop_index(batch_op.f('ix_stories_feature_id'))

    op.drop_table('stories')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_project_id'))
        batch_op.drop_index(batch_op.f('ix_features_epic_id'))

    op.drop_table('features')
    with op.batch_alter_table('workspace_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_user_email'))
        batch_op.drop_index(batch_op.f('ix_workspace_memberships_project_id'))

    op.drop_table('workspace_memberships')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_project_id'))

    op.drop_table('sprints')
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_releases_project_id'))

    op.drop_table('releases')
    with op.batch_alter_table('epics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_epics_project_id'))

    op.drop_table('epics')
    # ### end Alembic commands ###
